codepkg/objects/Department__c.object
<CustomObject>
    <label>Department</label>
    <nameField>
        <label>Department Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <referenceTo>Department__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <defaultValue>&quot;NoFirstName&quot;</defaultValue>
        <label>First Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/EmployeeManager.cls
public class EmployeeManager {
    
    public static Employee__c createEmployee(String lastName, String firstName, Id departmentId) {
        Employee__c employee = new Employee__c (
        	Name = lastName,
        	FirstName__c = firstName,
        	Department__c = departmentId
        );            
        
        Database.SaveResult sv = Database.insert(employee);
        return employee;
    }
    
    public static Boolean deleteEmployee(Id employeeId) {
        try {
       		delete new Employee__c(Id = employeeId);
        } catch(Exception ex) {
            return false;
        }
        
        return true;
    }
    
    public static Employee__c updateEmployee(Id employeeId, String lastName, String firstName) {
        Employee__c employee = new Employee__c(
            Id = employeeId,
        	Name = lastName,
        	FirstName__c = firstName        
        );            
        
        Database.SaveResult sv = Database.update(employee);
        return employee;
    }
    
    public static Employee__c getEmployeeById(Id employeeId) {
        Employee__c employee = [select Name from Employee__c where id = :employeeId];
        return employee;
    }
}