codepkg/objects/Office__c.object
<CustomObject>
    <fields>
        <fullName>Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Director</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Offices</relationshipLabel>
        <relationshipName>Offices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Office</label>
    <nameField>
        <label>Office Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OfficeManager.cls
public class OfficeManager {
    public static Office__c createOffice(String name, Id directorId) {
        Office__c office = new Office__c(
            Name = name,
            Director__c = directorId
        );
        Database.SaveResult sv = Database.insert(office);
        return office;
    }
    
     public static Office__c updateOffice(Id officeId, String name) {
        Office__c office = new Office__c(
            Id = officeId,
            Name = name
        );
        Database.SaveResult sv = Database.update(office);
        return office;
    }
    
    public static Boolean deleteOffice(Id officeId) {
        try {
       		delete new Office__c(Id = officeId);
        } catch(Exception ex) {
            return false;
        }
        return true;
    }
    
    public static Office__c getOfficeById(Id officeId) {
        Office__c office = [select Name, Director__c from Office__c where id = :officeId];
        return office;
    }
}